apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/habib-dubizzle/argo-app.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
