apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drivethru-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: backend.drivethru.com
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: drivethru-service
            port:
              number: 80

      - path: /status
        pathType: Prefix
        backend:
          service:
            name: drivethru-service
            port:
              number: 80
