
apiVersion: v1
kind: Service
metadata:
  name: drivethru-service
  namespace: "default"
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8989
  selector:
    app: drivethru